#! /usr/bin/env bash

# ===============================================

script_root="$( cd -- "${BASH_SOURCE[0]%/*}" && pwd -P )"
. "${script_root}/lib/helpers.bash"

# ===============================================

tools=(
  az
  aws
  granted
  gcloud
  terraform
  terragrunt
)

version_az()          { az version | jq -j '."azure-cli"'; }
version_aws()         { aws --version | grep -Po "aws-cli/\K\S+"; }
version_granted()     { granted --version | awk -F' ' '{print $NF}'; }
version_gcloud()      { gcloud version | grep -Po "Google Cloud SDK \K\S+"; }
version_terraform()   { terraform version -json | jq -r .terraform_version; }
version_terragrunt()  { terragrunt -v | awk -F' ' '{print $NF}'; }

# ===============================================

install_az() {
  with_tmp
  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
}

install_aws() {
  with_tmp
  curl -sLO "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  unzip awscli-exe-linux-x86_64.zip
  sudo ./aws/install "${@}"
}

install_granted() {
  with_tmp
  curl -sLO releases.commonfate.io/granted/v0.36.2/granted_0.36.2_linux_x86_64.tar.gz
  sudo tar -zxvf ./granted_0.36.2_linux_x86_64.tar.gz -C /usr/local/bin/
  sudo ln -sf /usr/local/bin/granted /usr/local/bin/assumego
}

install_gcloud() {
  apt_setup \
    "https://packages.cloud.google.com/apt/doc/apt-key.gpg" google-cloud-sdk.gpg \
    "https://packages.cloud.google.com/apt cloud-sdk main" google-cloud-sdk.list

  sudo apt-get update
  sudo apt-get -y install google-cloud-cli
}

install_terraform() {
  apt_setup \
    "https://apt.releases.hashicorp.com/gpg" hashicorp-archive-keyring.gpg \
    "https://apt.releases.hashicorp.com $(lsb_release -cs) main" hashicorp.list

  sudo apt-get update
  sudo apt-get -y install terraform
}

install_terragrunt() {
  with_tmp
  curl -sLO "https://github.com/gruntwork-io/terragrunt/releases/download/v0.91.1/terragrunt_linux_amd64"
  sudo install -o root -g root -m 0755 terragrunt_linux_amd64 /usr/local/bin/terragrunt
}

# ===============================================


case "${1}" in
  _commands) echo "${tools[*]}";;
  *)
    installer "${@}"
    status
  ;;
esac