#! /usr/bin/env bash

# ===============================================

script_root="$( cd -- "${BASH_SOURCE[0]%/*}" && pwd -P )"
. "${script_root}/lib/helpers.bash"

# ===============================================

tools=(
  az
  aws
  gcloud
  terraform
)

version_az()        { az version | jq -j '."azure-cli"'; }
version_aws()       { aws --version | grep -Po "aws-cli/\K\S+"; }
version_gcloud()    { gcloud version | grep -Po "Google Cloud SDK \K\S+"; }
version_terraform() { terraform version -json | jq -r .terraform_version; }

# ===============================================

install_az() {
  with_tmp
  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
}

install_aws() {
  with_tmp
  curl -sLO "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  unzip awscli-exe-linux-x86_64.zip
  sudo ./aws/install "${@}"
}

install_gcloud() {
  apt_setup \
    "https://packages.cloud.google.com/apt/doc/apt-key.gpg" google-cloud-sdk.gpg \
    "https://packages.cloud.google.com/apt cloud-sdk main" google-cloud-sdk.list

  sudo apt-get update
  sudo apt-get -y install google-cloud-cli
}

install_terraform() {
  apt_setup \
    "https://apt.releases.hashicorp.com/gpg" hashicorp-archive-keyring.gpg \
    "https://apt.releases.hashicorp.com $(lsb_release -cs) main" hashicorp.list

  sudo apt-get update
  sudo apt-get -y install terraform
}

# ===============================================


case "${1}" in
  _commands) echo "${tools[*]}";;
  *)
    installer "${@}"
    status
  ;;
esac