#! /usr/bin/env bash

# ===============================================

script_root="$( cd -- "${BASH_SOURCE[0]%/*}" && pwd -P )"
. "${script_root}/lib/helpers.bash"

# ===============================================

tools=(
  docker
  subl
  code
  slack
  teams
)

version_docker()    { docker --version | grep -Po "Docker version \K.+"; }
version_subl()      { subl --version | grep -Po "Sublime Text \K.+"; }
version_code()      { code --version | head -1 ; }
version_slack()     { slack --version; }
version_teams()     { teams-for-linux --version 2>/dev/null; }

# ===============================================

install_docker() {
  case ${CODENAME} in
    bullseye|bookworm|lunar|kinetic|jammy|focal) local codename=${CODENAME} ;;
    *) local codename=bookworm ;;
  esac

  apt_setup \
    "https://download.docker.com/linux/${DISTRO}/gpg" docker.gpg \
    "https://download.docker.com/linux/${DISTRO} ${codename} stable" docker-stable.list

  sudo apt-get update
  sudo apt-get -y install \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin
  sudo usermod -a -G docker $(whoami)
}

install_subl() {
  apt_setup \
    "https://download.sublimetext.com/sublimehq-pub.gpg" sublime.gpg \
    "https://download.sublimetext.com apt/stable/" sublime-text-stable.list

  sudo apt-get update
  sudo apt-get -y install sublime-text
}

install_code() {
  apt_setup \
    "https://packages.microsoft.com/keys/microsoft.asc" vscode.gpg \
    "https://packages.microsoft.com/repos/code stable main" vscode.list

  sudo apt-get update
  sudo apt-get -y install code
}

install_slack() {
  apt_setup \
    "https://packagecloud.io/slacktechnologies/slack/gpgkey" slack-desktop.gpg \
    "https://packagecloud.io/slacktechnologies/slack/debian jessie main" slack-desktop.list

  sudo apt-get update
  sudo apt-get -y install slack-desktop
}

install_teams() {
  apt_setup \
    "https://repo.teamsforlinux.de/teams-for-linux.asc" teams-for-linux.gpg \
    "https://repo.teamsforlinux.de/debian/ stable main" teams-for-linux.list

  sudo apt-get update
  sudo apt-get -y install teams-for-linux
  sudo install -o root -g root -m 0755 $(which teams-for-linux) /usr/local/bin/teams
}

# ===============================================

case "${1}" in
  _commands) echo "${tools[*]}";;
  *)
    installer "${@}"
    status
  ;;
esac
