#! /usr/bin/env bash

# ===============================================

script_root="$( cd -- "${BASH_SOURCE[0]%/*}" && pwd -P )"
. "${script_root}/lib/helpers.bash"

# ===============================================

tools=(
  docker
  subl
  slack
  teams
)

version_docker()    { docker --version | grep -Po "Docker version \K.+"; }
version_subl()      { subl --version | grep -Po "Sublime Text \K.+"; }
version_slack()     { slack --version; }
version_teams()     { teams-for-linux --version; }

# ===============================================

install_docker() {
  apt_setup \
    "https://download.docker.com/linux/${DISTRO}/gpg" docker.gpg \
    "https://download.docker.com/linux/${DISTRO} ${CODENAME} stable" docker-stable.list

  sudo apt-get update
  sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
  sudo usermod -a -G docker $(whoami)
}

install_subl() {
  apt_setup \
    "https://download.sublimetext.com/sublimehq-pub.gpg" sublime.gpg \
    "https://download.sublimetext.com apt/stable/" sublime-text-stable.list

  sudo apt-get update
  sudo apt-get -y install sublime-text
}

install_slack() {
  apt_setup \
    "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC6ABDCF64DB9A0B2" slack-desktop.gpg \
    "https://packagecloud.io/slacktechnologies/slack/debian jessie main" slack-desktop.list

  sudo apt-get update
  sudo apt-get -y install slack-desktop
}

install_teams() {
  apt_setup \
    "https://repo.teamsforlinux.de/teams-for-linux.asc" teams-for-linux.gpg \
    "https://repo.teamsforlinux.de/debian/ stable main" teams-for-linux.list

  sudo apt-get update
  sudo apt-get -y install teams-for-linux
  sudo install -o root -g root -m 0755 $(which teams-for-linux) /usr/local/bin/teams
}

# ===============================================

installer "${@}"
status
