#! /usr/bin/env bash

# ===============================================

script_root="$( cd -- "${BASH_SOURCE[0]%/*}" && pwd -P )"
. "${script_root}/lib/helpers.bash"

# ===============================================

tools=(
  nvm
  node
  npm
  yarn
)

version_nvm()   { nvm -v; }
version_node()  { node --version; }
version_npm()   { npm --version; }
version_yarn()  { yarn --version; }

# ===============================================

preinstall () {
  [ "${1}" = npm ] && exit
}

install_nvm() {
  curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
}

init_nvm() {
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
}

install_node() {
  init_nvm
  command -v nvm >/dev/null 2>&1 || _install nvm
  init_nvm && nvm install node 2>&1
}

install_yarn() {
  init_nvm
  command -v npm >/dev/null 2>&1 || _install node
  init_nvm && npm install --global yarn
}

# ===============================================

case "${1}" in
  _commands) echo "${tools[*]}";;
  *)
    installer "${@}"
    init_nvm
    status
  ;;
esac