#! /usr/bin/env bash

# === [ANSI] ====================================

RESET='\e[0m'
CYAN='\e[1;36m'

# ===============================================

tools=(
  az
  aws
  gcloud
)

# ===============================================

version_az()      { az version | jq -j '."azure-cli"'; }
version_aws()     { aws --version | grep -Po "aws-cli/\K\S+"; }
version_gcloud()  { gcloud version | grep -Po "Google Cloud SDK \K\S+"; }

# ===============================================

_install () {(
  local tmp_dir="$(mktemp -d /tmp/install-XXXXX)"
  cd "${tmp_dir}"
  echo -e "${CYAN}Installing ${1}${RESET}"
  "install_${1}" | sed "s/^/\r  /"
  rm -rf "${tmp_dir}"
)}

_status() {
  local cmd="${1}"
  if command -v "${cmd}" >/dev/null 2>&1; then
    local is_installed='✓'
    local version="$(version_${cmd})";
  else
    local is_installed=' '
    local version="";
  fi
  printf "${is_installed}  %-12s %s\n" "${cmd}" "${version}"
}

# ===============================================

install_az() {
  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
}

install_aws() {
  curl -sLO "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  unzip awscli-exe-linux-x86_64.zip
  sudo ./aws/install "${@}"
}

install_gcloud() {
  _apt_setup \
    "https://packages.cloud.google.com/apt/doc/apt-key.gpg" \
    google-cloud-sdk.gpg \
    "https://packages.cloud.google.com/apt cloud-sdk main" \
    google-cloud-sdk.list

  sudo apt-get update
  sudo apt-get install google-cloud-cli
}

_apt_setup() {
  local keyring=/etc/apt/trusted.gpg.d
  sudo mkdir -p "${keyring}"
  curl -fsSL "${1}" \
    | sudo gpg --yes --dearmor -o "${keyring}/${2}"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=${keyring}/${2}] ${3}" \
    | sudo tee "/etc/apt/sources.list.d/${4}"
}

# ===============================================

status() {
  echo -e "${CYAN}Status ${1}${RESET}"
  for cmd in "${tools[@]}"; do
    _status "${cmd}"
  done
}

# ===============================================

case "${1}" in
  az|aws|gcloud) _install "${@}" ;;
esac

status
