#! /usr/bin/env bash

# === [ANSI] ====================================

RESET='\e[0m'
CYAN='\e[1;36m'

# ===============================================

tools=(
  jq
  curl
  wget
  file
  unzip
  git
  tree
  tmux
  zsh
  vim
  gpg
)

packages=(
  fd-find
  man-db
  lsb-release
  dnsutils
  iputils-ping
  universal-ctags
)

_install() {
  echo -e "\n${CYAN}Installing${RESET} (${@})"
  if command -v apt-get &>/dev/null; then
    sudo apt-get update && sudo apt-get install -f ${@}
  else
    echo pkg manager not implemented
  fi
}

_check() {
  echo -e "${CYAN}Status ${1}${RESET}"
  local missing=()

  for pkg in "${tools[@]}" "${packages[@]}"; do
    if dpkg -s "${pkg}" &>/dev/null; then
      local is_installed='✓'
    else
      local is_installed=' '
      missing+="${pkg}"
    fi
    printf "${is_installed}  %s\n" "${pkg}"
  done

  [ ${#missing[@]} -ne 0 ] \
    && _install "${missing[@]}" \
    || echo "Everything installed"
}

_post_install() {
  sudo install -o root -g root -m 0755 $(which fdfind) /usr/local/bin/fd
}

_check
_post_install
