#! /usr/bin/env bash


DISTRO="$(lsb_release -is | tr '[:upper:]' '[:lower:]')"
CODENAME="$(lsb_release -cs)"

_apt_setup() {
  local keyring=/etc/apt/trusted.gpg.d
  sudo mkdir -p "${keyring}"
  curl -fsSL "${1}" \
    | sudo gpg --yes --dearmor -o "${keyring}/${2}"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=${keyring}/${2}] ${3}" \
    | sudo tee "/etc/apt/sources.list.d/${4}"
}

_apt_setup \
  "https://download.docker.com/linux/${DISTRO}/gpg" \
  docker.gpg \
  "https://download.docker.com/linux/${DISTRO} ${CODENAME} stable" \
  docker-stable.list

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
sudo usermod -a -G docker ${USER}

