#! /usr/bin/env bash


DISTRO="$(lsb_release -is | tr '[:upper:]' '[:lower:]')"
CODENAME="$(lsb_release -cs)"

_apt_setup() {
  local keyring=/etc/apt/trusted.gpg.d
  sudo mkdir -p "${keyring}"
  curl -fsSL "${1}" \
    | sudo gpg --yes --dearmor -o "${keyring}/${2}"
  echo "deb [arch=$(dpkg --print-architecture) signed-by=${keyring}/${2}] ${3}" \
    | sudo tee "/etc/apt/sources.list.d/${4}"
}

_apt_setup \
  "https://download.sublimetext.com/sublimehq-pub.gpg" \
  sublime.gpg \
  "https://download.sublimetext.com apt/stable/" \
  sublime-text.list

sudo apt-get update
sudo apt-get install sublime-text
